version: '3.7'

services:

  database:
    image: postgres
    volumes:
      - ./docker/postgresql/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: '123456'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'stock'